# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f59cb1dd9e7eea52a6a2e3d98d8b0aa0a53dce6bf9c3a1dcc7ebce2809e9118be26ca1708256075fee8f21d858a78f8cb2ee1fb5ef694da23f30d11f27e2fa93

test:
  secret_key_base: 0ce6aef0fd9acfaeb722007d50930431e6ab5e0ed5af4c420de09e8789890488a3561fc45ac9c5d19b71841672bc0da17fcdd1f71f356a4db7b89c5b871cb208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
